apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
type: Opaque
stringData:
  POSTGRES_USER: vikunja
  POSTGRES_PASSWORD: vikunja
  VIKUNJA_DATABASE_USER: vikunja
  VIKUNJA_DATABASE_PASSWORD: vikunja
